### ISSUE TITLE
"Error while parsing" infinite recursion

### ISSUE THREAD

**Issue by voneiden** [xesscorp/zyc#2]
* zyc version: 0.3.0
* Python version: 3.8.5
* Operating System: Gentoo Linux / AwesomeWM

### Description

Attempted to open a footprint, which failed, but instead of receiving a single notification zyc got stuck recursing  "Error while parsing" errors, implying that `null_module_text` isn't quite working right?

### What I Did

Attempted to open the following footprint: https://github.com/SnowMB/pcb_library/blob/master/footprints.pretty/Molex_KK-254_1x08_P2.54mm_Horizontal.kicad_mod

No traceback, just a lot of error dialogs. :-) 

![2020-09-12-010254_2560x1440_scrot](https://user-images.githubusercontent.com/437576/92977152-e86cc100-f494-11ea-8d16-df3c40172982.png)

**Comment by xesscorp** [comment]
I'm getting a parse error with this footprint, but not an infinite recursion. I'll investigate further.

**Comment by xesscorp** [comment]
The infinite recursion was caused by running a footprint search that returned a list of footprints which all had parse errors. Upon a parse error, `zyc` defaults to displaying the first item in its list of footprints, but this also produces an error since all the footprints have parse errors. This initiates the infinite recursion. I set a flag to prevent the recursion from happening.

The footprints you tried to view all had parse errors because they used an `offset` keyword in the 3D model field of the footprint. `pykicad` expects the keyword to be `at` and throws a parse error. I have a [fork of `pykicad`](https://github.com/xesscorp/pykicad) that fixes this. I'll submit a PR to the master repo.
